
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            #- run: npm install --force
            #- run: npm update
            - run: |
                curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
                chmod +x ./snyk
                curl https://github.com/snyk/snyk-to-html.git -o snyk-to-html
                chmod +x ./snyk-to-html
                ./snyk auth $SNYK_TOKEN
                ./snyk monitor 
                ./snyk test --json | ./snyk-to-html -o sca_results.html
            - store_artifacts: #store SCA HTML artifact
                path: sca_results.html
                destination: sca_results.html
            - run: ./snyk code test --json | ./snyk-to-html -o code_results.html
            - store_artifacts: #store HTML output from custom script
                path: code_results.html
                destination: code_results.html
            - run: ./snyk container test amitsnyk/snyk-juice-shop:latest --json > container_results.json #replace amitsnyk/snyk-juice-shop:latest with your image name.
            - store_artifacts: #store container json output generated by snyk
                path: container_results.json
                destination: container_results.json
            - run: ./snyk iac test --json > iac_results.json
            - store_artifacts: #store iac json output generated by snyk
                path: iac_results.json
                destination: iac_results.json
        workflows: null
