
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            #- run: npm install --force
            #- run: npm update
            - run: | #install Snyk CLI tool and snyk-to-html + authenticate into Snyk
                curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
                chmod +x ./snyk
                curl -L https://github.com/snyk/snyk-to-html/releases/download/v2.3.1/snyk-to-html-linux -o snyk-to-html
                chmod +x ./snyk-to-html
                ./snyk auth $SNYK_TOKEN
            - run: ./snyk test --severity-threshold=critical --json | ./snyk-to-html -o sca_results.html || true #SCA scan with severity threshold set to high
            - store_artifacts: #store SCA HTML artifact
                path: sca_results.html
                destination: sca_results.html
            - run: ./snyk code test --json | ./snyk-to-html -o code_results.html || true #SAST code scan
            - store_artifacts: #store HTML output from custom script
                path: code_results.html
                destination: code_results.html
            - run: ./snyk container test amitsnyk/snyk-juice-shop:latest --json > container_results.json || true #Container image scan - replace amitsnyk/snyk-juice-shop:latest with your registry/image_name:tag.
            - store_artifacts: #store container json output generated by Snyk
                path: container_results.json
                destination: container_results.json
            - run: ./snyk iac test --json > iac_results.json || true #IaC scan
            - store_artifacts: #store iac json output generated by Snyk
                path: iac_results.json
                destination: iac_results.json
        workflows: null
