
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
    build:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - run: npm install --force
            - run: npm update
            - run:
                name: install-snyk-code-test-report
                command: curl https://raw.githubusercontent.com/adamsnyk/snyk-code-test-handler/master/code_test_report/__main__.py > code_test_report.py
            #- snyk/scan:
            #    fail-on-issues: false
            #    monitor-on-build: true
            #    token-variable: SNYK_TOKEN
            #    additional-arguments: --container amitsnyk/snyk-juice-shop:latest --app-vulns
            - snyk/scan:
                fail-on-issues: false
                monitor-on-build: false
                token-variable: SNYK_TOKEN
                additional-arguments: --code --json > output.json
            - store_artifacts:
                path: output.json
                destination: output.json
            - run:
                name: run-code-report
                command: cat output.json | python3 code_test_report.py
            - store_artifacts:
                path: output.html
                destination: output.html
            - run:
                name: remove-run-code-report
                command: rm code_test_report.py
        workflows: null
